In [2]:
#Bibliotecas

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
from sklearn.naive_bayes import GaussianNB


In [5]:
# /Risco o R fica com defeito fazendo o arquivo gerar um erro de size limit
# Colocando o arquivo em uma variável
base_risco_credito = pd.read_csv('Base_de_dados\irsco_credito.csv')

In [6]:
base_risco_credito

historia divida garantias     renda     risco
0           ruim   alta   nenhuma      0_15      alto
1   desconhecida   alta   nenhuma     15_35      alto
2   desconhecida  baixa   nenhuma     15_35  moderado
3   desconhecida  baixa   nenhuma  acima_35      alto
4   desconhecida  baixa   nenhuma  acima_35     baixo
5   desconhecida  baixa  adequada  acima_35     baixo
6           ruim  baixa   nenhuma      0_15      alto
7           ruim  baixa  adequada  acima_35  moderado
8            boa  baixa   nenhuma  acima_35     baixo
9            boa   alta  adequada  acima_35     baixo
10           boa   alta   nenhuma      0_15      alto
11           boa   alta   nenhuma     15_35  moderado
12           boa   alta   nenhuma  acima_35     baixo
13          ruim   alta   nenhuma     15_35      alto

RISCO CREDITO

Pré processamento de dados
Separando as variáveis: X previsores Y as classes

In [8]:
# Previsores
X_risco_credito = base_risco_credito.iloc[:, 0:4].values
X_risco_credito
# pegando todos os valores da base de dados menos a 4 coluna, responsável pela classe

array([['ruim', 'alta', 'nenhuma', '0_15'],
       ['desconhecida', 'alta', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'adequada', 'acima_35'],
       ['ruim', 'baixa', 'nenhuma', '0_15'],
       ['ruim', 'baixa', 'adequada', 'acima_35'],
       ['boa', 'baixa', 'nenhuma', 'acima_35'],
       ['boa', 'alta', 'adequada', 'acima_35'],
       ['boa', 'alta', 'nenhuma', '0_15'],
       ['boa', 'alta', 'nenhuma', '15_35'],
       ['boa', 'alta', 'nenhuma', 'acima_35'],
       ['ruim', 'alta', 'nenhuma', '15_35']], dtype=object)

In [9]:
Y_risco_credito = base_risco_credito.iloc[:, 4].values
# de todos os valores apenas a 4 coluna, sem intervalo 0:{algum valor}
Y_risco_credito

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [10]:
# Conversão para atributos em números ao invés de string

from sklearn.preprocessing import LabelEncoder

label_encoder_historia = LabelEncoder()
label_encoder_divida = LabelEncoder()
label_encoder_garantia = LabelEncoder()
label_encoder_renda = LabelEncoder()

In [12]:
# nova célula de código aplicar os precessamentos

X_risco_credito[:,0] = label_encoder_historia.fit_transform(X_risco_credito[:,0])
X_risco_credito[:,1] = label_encoder_divida.fit_transform(X_risco_credito[:,1])
X_risco_credito[:,2] = label_encoder_garantia.fit_transform(X_risco_credito[:,2])
X_risco_credito[:,3] = label_encoder_renda.fit_transform(X_risco_credito[:,3])

X_risco_credito 
#transforma toda a base de string para números de atributo a atributo para usar os métodos de processamento
# tranformação de atributos categóricos para numéricos

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [14]:
#salvando os arquivos 

import pickle

#  {nome do arquivo} , 'wb' para salvar
with open('riso_credito.pkl', 'wb') as f:
    pickle.dump([X_risco_credito, Y_risco_credito], f)

Algorítmo Naive bayes aplicado


In [17]:
# algoritmo Naive bayes através da classe GaussianNB
naive_risco_credito = GaussianNB()

# fit -> encaixar, algoritmo vai ser encaixado nesses dados 
naive_risco_credito.fit(X_risco_credito, Y_risco_credito)
#                  atributos previsores, resultados esperados

#Algoritmo já foi criado, agora é gerar as previsões 

GaussianNB()

In [18]:
#previsões usando o algoritmo naive bayes atribuindo novos dados separados por [] com base nos resultados obtidos no encoder transform
previsao = naive_risco_credito.predict([[0,0,1,2],[2,0,0,0]])
#função predict retorna apenas a classe

In [22]:
previsao

array(['baixo', 'moderado'], dtype='<U8')

In [21]:
#probabilidades 
naive_risco_credito.class_prior_

array([0.42857143, 0.35714286, 0.21428571])

BASE CREDIT DATA

In [4]:
import pickle
# O arquivo credit.pkl tem todos esses dados separados, abrindo o arquivo e exportando o seu conteúdo parar fora
with open('credit.pkl','rb') as f:
    X_credit_treinamento, y_credit_treinamento, X_credit_test, y_credit_teste = pickle.load(f)

In [5]:
X_credit_treinamento.shape, y_credit_treinamento.shape

((1500, 3), (1500,))

In [6]:
naive_credit_data = GaussianNB() #algoritmo naive 
naive_credit_data.fit(X_credit_treinamento, y_credit_treinamento) #treinamento

GaussianNB()

In [7]:
# Concluido o treinamento, hora de fazer as previosões 
previsoes = naive_credit_data.predict(X_credit_test)

In [ ]:
previsoes 

In [11]:
# comparando os resultados (arrays)
from sklearn.metrics import accuracy_score, confusion_matrix

In [10]:
accuracy_score(y_credit_teste, previsoes)

0.938

In [12]:
confusion_matrix(y_credit_teste, previsoes)

array([[428,   8],
       [ 23,  41]], dtype=int64)

BASE DE DADOS CENSUS

In [13]:
import pickle 
with open('census.pkl','rb') as f:
    X_census_treinamento, y_census_treinamento, X_census_teste, y_census_teste = pickle.load(f)

In [14]:
naive_base_census = GaussianNB()
naive_base_census.fit(X_census_treinamento, y_census_treinamento)

GaussianNB()

In [16]:
preview = naive_base_census.predict(X_census_teste)
preview

array([' >50K', ' >50K', ' >50K', ..., ' <=50K', ' >50K', ' >50K'],
      dtype='<U6')

In [17]:
accuracy_score(y_census_teste, preview) #jogar cara ou coroa fica muito melhor pois a chance de 47% é muito baixa e imprecisa 

0.4767656090071648